# Generated by Django 5.2.5 on 2025-08-26 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scheduletemplate',
            name='unique_template_per_owner_group_name',
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='scheduletemplate',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='unique_template_per_group_name'),
        ),
    ]
