# Generated by Django 5.2.5 on 2025-08-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('user_name', models.CharField(max_length=255)),
                ('day', models.PositiveSmallIntegerField()),
                ('value', models.CharField(blank=True, max_length=16)),
            ],
            options={
                'unique_together': {('year', 'month', 'user_name', 'day')},
            },
        ),
    ]
