# Generated by Django 5.2.5 on 2025-08-26 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pierwsza_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cell',
            options={'ordering': ['year', 'month', 'day', 'user_name']},
        ),
        migrations.AlterUniqueTogether(
            name='cell',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cell',
            name='day',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='cell',
            name='month',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['year', 'month'], name='pierwsza_ap_year_5316a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='cell',
            constraint=models.UniqueConstraint(fields=('year', 'month', 'user_name', 'day'), name='unique_cell_per_day'),
        ),
    ]
